config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
urlpatterns = [
    path("<int:pk>", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add_photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete",
        views.delete_photo,
        name="delete_photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
    path("upload-room", views.UploadRoomView.as_view(), name="add_room"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("change-password/", views.ChangePasswordView.as_view(), name="password"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    &copy; 2020 Airbnb, Inc. All rights reserved.
</footer>

templates/partials/nav.html
<ul class="flex items-center tex-sm font-medium h-full">
    {% if user.is_authenticated %}
        <li class="nav_link"><a href="{% url 'rooms:add_room' %}">Upload Room</a></li>
        <li class="nav_link"><a href="{{ user.get_absolute_url }}">Profile</a></li>
        <li class="nav_link"><a class="py-10" href="{% url 'users:logout' %}">Log out</a></li>
    {% else %}
        <li class="nav_link"><a href="{% url 'users:login' %}">Login</a></li>
        <li class="nav_link"><a href="{% url 'users:signup' %}">Sign Up</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <span class="btn border border-gray-700 border-2 text-gray-700 mb-2">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>Continue with Github
    </span>
    <span class="btn bg-yellow-400 text-yellow-800 mb-2">
        <i class="fas fa-comment mr-2 fa-lg"></i>Continue with Kakao
    </span>
</div>
<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
        <span class="text-gray-600 text-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>