config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
urlpatterns = [
    path("<int:pk>", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add_photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete",
        views.delete_photo,
        name="delete_photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
    path("upload-room", views.UploadRoomView.as_view(), name="add_room"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    pass

    class Meta:
        verbose_name = "Room Types"


class Amenity(AbstractItem):

    pass

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    pass

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    pass

    class Meta:
        verbose_name = "House Rules"


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)  # Call the real save() method

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        if len(all_reviews) == 0:
            return 0
        else:
            return round(all_ratings / len(all_reviews), 2)

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        try:
            photos = self.photos.all()[1:5]
            print(photos)
            return photos
        except ValueError:
            return None


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models
from users import models as user_models


class SearchForm(forms.Form):
    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Room", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    pass


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = (
            "caption",
            "file",
        )

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        photo.room = models.Room.objects.get(pk=pk)
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.db.models import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django_countries import countries
from django.core.paginator import Paginator
from . import models, forms
from users import mixins


class HomeView(ListView):
    model = models.Room
    paginate_by = 12
    ordering = "price"
    paginate_orphans = 5
    context_object_name = "rooms"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class RoomDetailView(DetailView):
    model = models.Room


class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")
        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")
                paginator = Paginator(qs, 10, orphans=5)
                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)
                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()
        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(mixins.LoggedInOnlyView, UpdateView):
    model = models.Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    template_name = "rooms/edit_room.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if self.request.user.pk != room.host.pk:
            raise Http404()
        return room


class RoomPhotosView(mixins.LoggedInOnlyView, DetailView):
    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if self.request.user.pk != room.host.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host != user:
            pass
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.ObjectDoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(mixins.LoginRequiredMixin, UpdateView):
    model = models.Photo
    template_name = "rooms/edit_photo.html"
    fields = ("caption",)
    pk_url_kwarg = "photo_pk"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(mixins.LoggedInOnlyView, FormView):
    model = models.Photo
    template_name = "rooms/photo_create.html"

    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class UploadRoomView(mixins.LoggedInOnlyView, FormView):
    model = models.Room
    template_name = "rooms/room_create.html"
    form_class = forms.CreateRoomForm

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/edit_photo.html
{% extends "base.html" %}
{% block  pagename %}
    Edit Photo
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Update Photo" %}
    </div>
{% endblock content %}

templates/rooms/edit_room.html
{% extends "base.html" %}
{% block  pagename %}
    Edit Room
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Update Room" %}
        <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-400 font-medium">Edit Photos</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/photo_create.html
{% extends "base.html" %}
{% block  pagename %}
    Upload Photo
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Upload Photo" %}
    </div>
{% endblock content %}
{{form}}

templates/rooms/room_create.html
{% extends "base.html" %}
{% block  pagename %}
    Upload Room
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Upload Room" %}
    </div>
{% endblock content %}
{{form}}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% block  pagename %}
    About Room
{% endblock pagename %}
{% block  content %}
    <div class="-mt-5 container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-cover bg-center border border-gray-800 border-2" style = "background-image: url({{room.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div class = "h-1/2 w-1/2 bg-cover bg-center border border-gray-800 border-2" style = "background-image: url({{photo.file.url}})"></div>
            {% endfor %}
        </div>
    </div>
    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-gray-700 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=room.host %}
                    <span class="mt-1 text-gray500 text-sm">{{room.host.first_name}}</span>
                </a>
            </div>
            <div class="flex pb-5 border-b">
                <span class="mr-5 font-light">{{room.room_type}}</span>
                <span class="mr-5 font-light">{{room.beds}} bed{{room.beds|pluralize}}</span>
                <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
                <span class="mr-5 font-light">{{room.guests}} guest{{room.guests|pluralize}}</span>
            </div>
            <p class="mt-5 pb-5 border-b">
                {{room.description}}
            </p>
            <div class="mt-5 pb-5 border-b">
                <h4 class="font-medium text-lg mb-2">Amenities</h4>
                {% for a in room.amenities.all %}
                    <li class="pb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="mt-5 pb-5 border-b">
                <h4 class="font-medium text-lg mb-2">Facilities</h4>
                {% for f in room.facilities.all %}
                    <li class="pb-2">{{f}}</li>
                {% endfor %}
            </div>
            <div class="mt-5 pb-5 border-b">
                <h4 class="font-medium text-lg mb-2">House Rules</h4>
                {% for r in room.house_rules.all %}
                    <li class="pb-2">{{r}}</li>
                {% endfor %}
            </div>
            <div class="mt-5">
                <h4 class="font-medium text-2xl mb-2">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-sm text-teal-600"></i>
                        <span class="font-bold text-lg">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-3"></div>
                    <div class="text-lg">
                        <span class="font-bold mr-2">
                            {{room.reviews.count}}
                        </span>
                        <span>
                            review{{room.reviews.count|pluralize}}
                        </span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="mt-5 flex items-center">
                            <a class="mr-5" href='{{review.user.get_absolute_url}}'>
                                {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                            </a>
                            <div class="list-none">
                                <li class="font-medium">
                                    {{review.user.first_name}}
                                </li>
                                <li>
                                    {{review.created|date:'F Y'}}
                                </li>
                            </div>
                        </div>
                        <p class="border-b py-5">{{review.review}}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div>
        </div class="w-1/3">
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="block btn_link">Edit Room</a>
            {% else %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}
{% load static %}
{% block  pagename %}
    Home
{% endblock pagename %}
{% block  content %}
    <div class="container mx-auto pb-10">
        <div class="rounded-xl -mx-32 bg-gray-700 mx-auto mt-32 mb-16 h-50vh bg-cover bg-center" style="background-image: url({% static 'image/seoul.jpeg' %})"></div>
        <div class="flex flex-wrap -mx-32 mb-10">
            {% for room in rooms %}
                {% include "mixins/room_card.html" with room=room %}
            {% endfor %}
        </div>
        <div class="flex items-center justify-center">
            {% if page_obj.has_previous %}
                <a href = "?page={{ page_obj.previous_page_number }}" class="text-teal-400">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}
            <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
            {% if page_obj.has_next %}
                <a href = "?page={{ page_obj.next_page_number }}" class="text-teal-400">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}
{% block  pagename %}
    {{room.name}}'s photos
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container mx-auto my-10 flex flex-col">
        <div class="my-10 w-full">
            <a class="btn_link px-3 w-1/6 block" href="{% url 'rooms:add_photo' room.pk %}">Add Photo</a>
        </div>
        {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items center">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-lg">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col mb-5 justify-center">
                    <a class="mb-5 rounded-lg bg-teal-500 border text-center text-white" href="{% url 'rooms:edit_photo' room.pk photo.pk %}">Edit</a>
                    <a class="border px-2 bg-red-600 rounded-lg text-center text-white" href="{% url 'rooms:delete_photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}
        <div class="flex justify-center">
            <a class="text-teal-500 font-medium text-xl mt-5" href="{{room.get_absolute_url}}/edit">Back to Room</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}
{% block  pagename %}
    Search
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <h2>Search!</h2>
    <form method="GET" action="{% url 'rooms:search' %}">
        {{form.as_p}}
        <button>Search</button>
    </form>
    <h3>Results</h3>

    {% for room in rooms %}
        <h3>{{room.name}}</h3>
    {% endfor %}
{% endblock content %}