config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("change-password/", views.ChangePasswordView.as_view(), name="password"),
]

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.shortcuts import reverse


class User(AbstractUser):

    """ Custom User Model """

    GENDER_MALE = "Male"
    GENDER_FEMALE = "Female"
    GENDER_OTHER = "Other"
    LANGUAGE_KOREAN = "kr"
    LANGUAGE_ENGLISH = "en"
    CURRENCY_USD = "usd"
    CURRENCY_KRW = "krw"
    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )
    LANGUAGE_CHOICES = ((LANGUAGE_KOREAN, "Korean"), (LANGUAGE_ENGLISH, "English"))
    CURRENCY_CHOICES = ((CURRENCY_USD, "USD"), (CURRENCY_KRW, "KRW"))
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True)
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=10, null=True, blank=True
    )
    bio = models.TextField(default="", blank=True)
    birthdate = models.DateField(null=True)
    language = models.CharField(
        choices=LANGUAGE_CHOICES, max_length=2, null=True, blank=True
    )
    currency = models.CharField(
        choices=CURRENCY_CHOICES, max_length=3, null=True, blank=True
    )
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Airbnb Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["first_name", "last_name", "email"]
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm password"}),
        label="confirm password",
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("User already exists with this email")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("password confirmation doest not match")
        else:
            return password1

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        username = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = username
        user.set_password(password)
        user.save()

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, reverse
from django.views.generic import View, FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    # success_url = reverse_lazy("core:home")
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(FormView):
    template_name = "users/signup.html"
    success_url = reverse_lazy("core:home")
    form_class = forms.SignUpForm

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
    except models.User.DoesNotExist:
        pass
    return redirect(reverse("core:home"))


class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, UpdateView):
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "avatar",
        "gender",
        "bio",
        "birthdate",
        "language",
        "currency",
    )

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "first_name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "last_name"}
        form.fields["avatar"].widget.attrs = {"placeholder": "avatar"}
        form.fields["gender"].widget.attrs = {"placeholder": "gender"}
        form.fields["bio"].widget.attrs = {"placeholder": "bio"}
        form.fields["birthdate"].widget.attrs = {"placeholder": "birthdate"}
        form.fields["language"].widget.attrs = {"placeholder": "language"}
        form.fields["currency"].widget.attrs = {"placeholder": "currency"}

        return form


class ChangePasswordView(mixins.LoggedInOnlyView, PasswordChangeView):
    template_name = "users/update-password.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {"placeholder": "old password"}
        form.fields["new_password1"].widget.attrs = {"placeholder": "new password"}
        form.fields["new_password2"].widget.attrs = {
            "placeholder": "new password confirmation"
        }
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()

templates/users/login.html
{% extends "base.html" %}
{% block  pagename %}
    Login
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'partials/social_login.html' %}
        {% include 'mixins/auth/auth_form.html' with form=form cta="Login" %}
        <div class="mt-2">
            <span class="mr-2">Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-teal-600 font-medium">Sign up</a>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}
{% block  pagename %}
    Sign Up
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'partials/social_login.html' %}
        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign Up" %}
        <div class="mt-2">
            <span class="mr-2">Have an account?</span>
            <a href="{% url 'users:login' %}" class="text-teal-600 font-medium">Login</a>
        </div>
    </div>
{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}
{% block  pagename %}
    Login
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class= "min-h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include 'mixins/auth/auth_form.html' with form=form cta="Change Password" %}
        </div>
    </div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}
{% block  pagename %}
    Login
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update" %}
        <div class="mt-5">
            <a href="{% url 'users:password' %}" class="text-teal-500 font-medium">Change Password</a>
        </div>
    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}
{% block  pagename %}
    {{user_obj.first_name}}'s profile
{% endblock pagename %}
{% block  content %}
    <div class="h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include "mixins/user_avatar.html" with user=user_obj %}
            <div class="flex items-center">
                <span class="text-3xl mt-1">
                    {{user_obj.first_name}}
                </span>
                {% if user_obj.superhost %}
                    <i class="fas fa-check-circle text-teal-400 ml-1"></i>
                {% endif %}
            
            </div>
            <span class="text-lg mb-5">{{user_obj.bio}}</span>
            {% if user == user_obj %}
                <a href="{% url 'users:update' %}" class="btn_link" >Edit Profile</a>
            {% endif %}
        </div>
        {% if user_obj.rooms.count > 0 %}
            <div class="container mx-auto pb-10 flex flex-col items-center">
                <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s rooms</h3>
                <div class="flex flex-wrap -mx-32 mb-10">
                    {% for room in user_obj.rooms.all %}
                        {% include "mixins/room_card.html" with room=room %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}